data:
  root_dir: '/ds/audio/FakeOrReal/'
  version: "FakeOrReal" # LA_15, LA_19, LA_21 for testing, InTheWild, FakeOrReal
  data_type: 'time_frame' # 'time_frame' or 'CQT'
  aug_prob: 0.0

model:
  architecture: 'aasist'
  size: 'default'
  shared_first_last: False
  aasist_config: 'src/models/architectures/aasist/config/AASIST.conf'
  aasist_weights:  Null # 'src/models/architectures/aasist/models/weights/AASIST.pth'
  activation: 'softmax'

batch_size: 32
num_workers: 8
num_epochs: 50
lr: 0.001