data:
  root_dir: '/ds/audio/FakeOrReal/'
  version: "FakeOrReal" # LA_15, LA_19, LA_21 for testing, InTheWild, FakeOrReal
  data_type: 'mel' # 'time_frame' or 'CQT' or 'mel'
  aug_prob: 0.0
  mms: False
  spectogram: False
  mix_up: False

model:
  architecture: 'resnet_w_dilation'
  size: 'default'
  shared_first_last: True
  dim: 2
  conv1: {'in_channels': 9, 'out_channels': 16, 'kernel_size': 7, 'padding': 3, 'bias': False} # in_channels = 10 for mms = True
  bn1: {'num_features': 16}
  resnet:
    blocks: [{'in_channels': 16, 'out_channels': 32, 'max_pool_ks': 2},
             {'in_channels': 32, 'out_channels': 64, 'max_pool_ks': 2},
             {'in_channels': 64, 'out_channels': 128, 'max_pool_ks': 2},
             {'in_channels': 128, 'out_channels': 256, 'max_pool_ks': 2},
             {'in_channels': 256, 'out_channels': 256, 'max_pool_ks': 8}]
    conv_kernel_size: 3
    padding: 2
    dilation: 2 # 1 for no dilation, add 1 to padding for each addition to dilation to keep the same dimensions
  fc1: {'in_features': 256, 'out_features': 64}
  fc2: {'in_features': 64, 'out_features': 32}
  out: {'in_features': 32, 'out_features': 2}
  activation: 'softmax'


batch_size: 128 # use 64 for actual training
num_workers: 32 # use 32 for actual training
num_epochs: 50
lr: 0.001