data:
  root_dir: '/ds/audio/LA_19/'
  version: "LA_19" # LA_15, LA_19, LA_21 for testing, InTheWild, FakeOrReal
  data_type: 'time_frame' # 'time_frame' or 'CQT'
  aug_prob: 0.0

model:
  architecture: 'resnet'
  size: 'small'
  shared_first_last: True
  dim: 1
  conv1: {'in_channels': 1, 'out_channels': 16, 'kernel_size': 7, 'padding': 3, 'bias': False}
  bn1: {'num_features': 16}
  resnet:
    blocks: [{'in_channels': 16, 'out_channels': 32, 'max_pool_ks': 4},
             {'in_channels': 32, 'out_channels': 64, 'max_pool_ks': 4},]
    conv_kernel_size: 3
    padding: 1
  fc1: {'in_features': 64, 'out_features': 32}
  fc2: {'in_features': 32, 'out_features': 16}
  out: {'in_features': 16, 'out_features': 2}
  activation: 'softmax'


batch_size: 64
num_workers: 8
num_epochs: 50
lr: 0.001